### ISSUE TITLE
Question regarding authority codes: `cnt` vs `lcnt`

### ISSUE THREAD

**Issue by ribose-jeffreylau** [CalConnect/csd-transcription-systems#32]
`Lao Commission Nationale de Toponymie` is represented twice in `sources/data/authority-codes.csv`, once by `cnt` and once by `lcnt`.

`lcnt` is used in `sources/data/codes.csv` whereas there's no usage of `cnt`.

Question is if `cnt` can be removed from `sources/data/authority-codes.csv` since it looks like a mistake?  Or is there any reason to keep both?

**Comment by ronaldtse** [comment]
Let's just use `cnt` because the BGN/PCGN description says:
"This system is based on the Lao Commission Nationale de Toponymie (CNT) system ..."

**Comment by ronaldtse** [comment]
Thanks for finding this.
